objects/ArchivedFeedComment__c.object
<CustomObject>
    <fields>
        <fullName>ArchivedFeedItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ArchivedFeedItem</label>
        <referenceTo>ArchivedFeedItem__c</referenceTo>
        <relationshipLabel>ArchivedFeedComments</relationshipLabel>
        <relationshipName>ArchivedFeedComments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ArchivedFeedComment</label>
    <nameField>
        <label>ArchivedFeedComment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ArchivedFeedComments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ArchivedFeedItem__c.object
<CustomObject>
    <label>Archived Feed Item</label>
    <nameField>
        <label>ArchivedFeedItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Archived Feed Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ChatterAuditDeleteItemsByPostIdBatch.cls
global class ChatterAuditDeleteItemsByPostIdBatch implements Database.Batchable<SObject>, Database.Stateful{	
	
	/**
	 * Batch Start Method
	 *
	 * @param ctx
	 * @return				String with query
 	 */
    global Database.queryLocator start(Database.BatchableContext ctx){
       // Will use a.ArchivedFeedItem__c = null as this field is a lookup, and this batch executes after deletion of parent record
        return Database.getQueryLocator( [Select a.Id
											From ArchivedFeedComment__c a
											where a.ArchivedFeedItem__c = null
											limit :ChatterAuditConstants.MAX_DML_ROWS_BATCH] );
    }
    
    /**
	 * Batch execute Method
	 *
	 * @param ctx
	 * @param data		List of Sobject
 	 */
    global void execute(Database.BatchableContext ctx, List<Sobject> results){
       this.deleteComments(results);
    }
    
    /**
	 * Batch Finish Method
	 *
	 * @param ctx
 	 */
    global void finish(Database.BatchableContext ctx){    	
    }
	
	/**
	 * Delete comments
	 * @param results -- list<Sobject>
	 **/
	public void deleteComments(List<Sobject> results){
		ChatterAuditUtils.setDeleteAllowedForPosts(true);
		delete results;
		ChatterAuditUtils.setDeleteAllowedForPosts(false);
	}	
}