objects/ArchivedChatterMessage__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ChatterMessageId__c</fullName>
        <externalId>true</externalId>
        <label>ChatterMessageId</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ConversationId__c</fullName>
        <externalId>true</externalId>
        <label>ConversationId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CreatedById__c</fullName>
        <label>CreatedById</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SenderId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SenderId</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Archived_Chatter_Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SentDate__c</fullName>
        <label>SentDate</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Archived Chatter Message</label>
    <nameField>
        <label>Archived Chatter Message</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Archived Chatter Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ChatterAuditSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Setup data for Chatter Compliance app</description>
    <fields>
        <fullName>ArchivedPMessagesJobId__c</fullName>
        <label>Archived Private Messages Job Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>ChatterComplianceSettings</label>
</CustomObject>

classes/ChatterAuditPrivateMessagesBatch.cls
global class ChatterAuditPrivateMessagesBatch implements Database.Batchable<SObject>, Database.Stateful{	
	
	private ChatterAuditSettings__c cSetting;
	private Datetime dateFilter;
	private boolean reschedule;
	
	/**
	 * Batch Constructor
	 * @param d -- Datetime with the date to use as filter in query (can be null, which equals get all p.messages)
	 * @param reschedule -- True if this batch should be rescheduled
	 **/
	 global ChatterAuditPrivateMessagesBatch( Datetime d, boolean reschedule ){
	 	this.cSetting = ChatterAuditSettings__c.getValues(ChatterAuditConstants.CUSTOM_SETTING_NAME);
	 	this.dateFilter = d;
	 	this.reschedule = reschedule;
	 }
	 
	 global ChatterAuditPrivateMessagesBatch( Datetime d ){
	 	this.cSetting = ChatterAuditSettings__c.getValues(ChatterAuditConstants.CUSTOM_SETTING_NAME);
	 	this.dateFilter = d;
	 	this.reschedule = false;
	 }  
	 
	 
	/**
	 * Batch Start Method
	 *
	 * @param ctx
	 * @return				String with query
 	 */
    global Database.queryLocator start(Database.BatchableContext ctx){
        return Database.getQueryLocator( this.getQuery() );
    }
    
    /**
	 * Batch execute Method
	 *
	 * @param ctx
	 * @param data		List of Sobject
 	 */
    global void execute(Database.BatchableContext ctx, List<Sobject> results){
       this.archiveMessages(results);
    }
    
    /**
	 * Batch Finish Method
	 *
	 * @param ctx
 	 */
    global void finish(Database.BatchableContext ctx){
    	if ( this.reschedule ){
    		 ChatterAuditUtils.privateMessagesScheduler();
    		 System.abortJob( this.cSetting.ArchivedPMessagesJobId__c );
    	}
    }
	
	/**
	 * Archiving private messages in custom object ArchivedChatterMessage
	 * @param results -- list<Sobject>
	 **/
	public void archiveMessages(List<Sobject> results){
		list<ArchivedChatterMessage__c> elms = new list<ArchivedChatterMessage__c>();
		for ( sObject obj : results ){
			ChatterMessage aux = (ChatterMessage) obj;
			ArchivedChatterMessage__c elm = new ArchivedChatterMessage__c();
			elm.Body__c = aux.Body;
			elm.ConversationId__c = aux.ConversationId;
			elm.CreatedById__c = aux.CreatedById;
			elm.SenderId__c = aux.SenderId;
			elm.SentDate__c = aux.SentDate;
			elm.ChatterMessageId__c = aux.Id; 
			elms.add(elm);
		}
		upsert elms;
	}
	
	/**
	 * Returns query for ChatterMessages
	 * @return String
	 **/
	public String getQuery(){
		String theDateFormated = (this.dateFilter != null) ? (this.dateFilter.formatGmt('yyyy-MM-dd HH:mm:ss')).replace(' ','T')+'.000Z' : '';
		String add = (this.dateFilter != null) ? 'where c.SentDate > '+theDateFormated : '';
		return 'Select c.SentDate, c.SenderId, c.Id, c.CreatedById, c.ConversationId, c.Body From ChatterMessage c '+add;
	} 
	
}