objects/ChatterAuditSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Setup data for Chatter Compliance app</description>
    <fields>
        <fullName>ArchivedPMessagesJobId__c</fullName>
        <label>Archived Private Messages Job Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ArchivedPMessagesUpdateLastExecution__c</fullName>
        <label>Archived Private Messages Update Last Ex</label>
        <type>DateTime</type>
    </fields>
    <label>ChatterComplianceSettings</label>
</CustomObject>

classes/ChatterAuditPrivateMessagesSch.cls
global class ChatterAuditPrivateMessagesSch implements Schedulable{
	
	/*
	 * Updating custom setting with job id and last executed time and call batch process
	 */
	global void execute(SchedulableContext sc) {
		ChatterAuditSettings__c cnf = ChatterAuditSettings__c.getValues(ChatterAuditConstants.CUSTOM_SETTING_NAME);
		Datetime dateToSend = cnf.ArchivedPMessagesUpdateLastExecution__c;
		cnf.ArchivedPMessagesUpdateLastExecution__c = Datetime.now();
		cnf.ArchivedPMessagesJobId__c = sc.getTriggerId();		
		upsert cnf;
		database.executebatch(  new ChatterAuditPrivateMessagesBatch(dateToSend,true) );		
   	} 
	
}